# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c003dbf984aa45945c8e716ab77b25bd9864d3821d199055db6275238e909a1edba8b11b22bc677c2eda9bd3f55dadc29643893ed180310fe2668d30b66417

test:
  secret_key_base: 83721ca1dd0388c8669d85e3b642fbacca70532ee7ede975711262eeacd5120d6ee25a165a6ac41de5e2760782f21cf033474304b4ef61daa043ba91502323ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
